# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Lint with flake8
        run: |
          flake8 python-otbr-api
      - name: Check formatting with black
        run: |
          black python-otbr-api --check --diff
      - name: Lint with mypy
        run: |
          mypy python-otbr-api
      - name: Lint with pylint
        run: |
          pylint python-otbr-api

